before:
  hooks:
    - go mod tidy

project_name: hosts
builds:
  - binary: hosts
    id: hosts
    goos:
      - linux
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/martinnirtl/hosts-cli/cmd.version={{ .Version }}
      - -X github.com/martinnirtl/hosts-cli/cmd.commit={{ .Commit }}
      - -X github.com/martinnirtl/hosts-cli/cmd.date={{ .Date }}
  - binary: hosts
    id: hosts-macos
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/martinnirtl/hosts-cli/cmd.version={{ .Version }}
      - -X github.com/martinnirtl/hosts-cli/cmd.commit={{ .Commit }}
      - -X github.com/martinnirtl/hosts-cli/cmd.date={{ .Date }}
    # hooks:
    #   post: 
    #     - gon gon.hcl

universal_binaries:
  - ids:
      - hosts-macos
    name_template: hosts
    replace: true
    # hooks:
    #   post: 
    #     - gon gon.hcl

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "darwin" }}macos
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

# sboms:
#   - artifacts: archive

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  abbrev: 0
  groups: # Regex use RE2 syntax as defined here: https://github.com/google/re2/wiki/Syntax.
    - title: 'Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: 'Documentation'
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 300
    - title: 'Dependency updates'
      regexp: '^.*?(feat|fix|chore)\(deps?.+\)!?:.+$'
      order: 400
    - title: 'Other work'
      order: 999
  filters:
    exclude:
      - '^test:'
      - '^.*?Bump(\([[:word:]]+\))?.+$'

release:
  prerelease: auto
  # # header: |
  # #   Welcome to this new release!
  # footer: |
  #   That's it for {{ .Tag }}!

brews:
  - name: hosts
    tap:
      owner: martinnirtl
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/martinnirtl/hosts-cli"
    description: "Manage host entries - a simple tool for a simple, but annoying task!"
