before:
  hooks:
    - go mod tidy

project_name: hosts
builds:
  - binary: hosts
    id: hosts
    goos:
      - linux
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/martinnirtl/hosts-cli/cmd.version={{ .Version }}
      - -X github.com/martinnirtl/hosts-cli/cmd.commit={{ .Commit }}
      - -X github.com/martinnirtl/hosts-cli/cmd.date={{ .Date }}
  - binary: hosts
    id: hosts-macos
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/martinnirtl/hosts-cli/cmd.version={{ .Version }}
      - -X github.com/martinnirtl/hosts-cli/cmd.commit={{ .Commit }}
      - -X github.com/martinnirtl/hosts-cli/cmd.date={{ .Date }}
    # hooks:
    #   post: 
    #     - gon gon.hcl

universal_binaries:
  - ids:
      - hosts-macos
    name_template: hosts
    replace: true
    # hooks:
    #   post: 
    #     - gon gon.hcl

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  mode: keep-existing

brews:
  - name: hosts
    tap:
      owner: martinnirtl
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/martinnirtl/hosts-cli"
    description: "Manage host entries - a simple tool for a simple, but annoying task!"

# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
